# Generated by Django 4.1.3 on 2022-12-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=150)),
                ('github', models.CharField(max_length=150)),
                ('resume', models.FileField(upload_to='uploads/file')),
            ],
        ),
    ]
