# Generated by Django 4.1.3 on 2022-12-20 05:01

import EmployeeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=models.FileField(upload_to='uploads/file'),
        ),
    ]
